name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches: [main]  # Change if your main branch has a different name
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install dependencies, build site, and generate .nojekyll
      - name: Build Astro site
        uses: withastro/action@v4
        with:
          path: .          # Root of your Astro project
          # node-version: 22   # Optional: specify Node version
          # package-manager: pnpm@latest  # Optional, auto-detected

      # 3. Create .nojekyll to prevent GitHub Pages from trying to use Jekyll
      - name: Disable Jekyll
        run: |
          touch dist/.nojekyll

      # 4. Deploy the built site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
        with:
          folder: dist  # Astro output folder
